#!/bin/bash

exec 1>&2
# Define colors
RED='\033[0;31m'
NC='\033[0m'

# Define term to search for
SEARCH_TERM="Fine"

# Check for the presence of the SEARCH_TERM in updated files
if [[ $(git log --oneline|head -1|awk '{print $2}') == *$SEARCH_TERM* ]]
then
	printf "${RED}Error:${NC} Found ${SEARCH_TERM} in attempted commit.\n"
	printf "Please remove all occurances of ${SEARCH_TERM} before committing.\n"
	exit 1
fi
